# -*- coding: utf-8 -*-
"""Movielens_GUI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKcYQgGMGByIYa6mtdWu1oNhJ2b0wtA9
"""

import pandas as pd
import joblib
import gradio as gr

tfidf = joblib.load("movie_tfidf.pkl")
similarity_tfidf = joblib.load("movie_similarity.pkl")
movies = pd.read_pickle("movies.pkl")

print("Files loaded successfully!")
print("Total movies:", len(movies))

def recommend_movies(movie_name):
    if not movie_name or not movie_name.strip():
        return pd.DataFrame({"Message": ["Please enter a movie title."]})

    search_name = movie_name.strip().lower()
    matches = movies[ movies["Title"].str.lower() == search_name]

    if matches.empty:
        matches = movies[
            movies["Title"].str.lower().str.contains(
                search_name, regex=False, na=False
            )
        ]

    if matches.empty:
        return pd.DataFrame({
            "Message": ["Movie not found. Please try another title."]
        })


    movie_index = matches.index[0]
    selected_title = movies.loc[movie_index, "Title"]


    scores = list(enumerate(similarity_tfidf[movie_index]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    scores = [
        (i, score) for i, score in scores
        if i != movie_index
    ]

    top_movies = scores[:5]
    recommendations = pd.DataFrame([
        {
            "Recommended Movie": movies.iloc[i]["Title"],
            "Similarity Score": round(float(score), 3)
        }
        for i, score in top_movies
    ])

    return recommendations

demo = gr.Interface(
    fn=recommend_movies,
    inputs=gr.Textbox(
        label="Enter a movie title",
        placeholder="For example: Toy Story"
    ),
    outputs=gr.Dataframe(
        headers=["Recommended Movie", "Similarity Score"],
        label="Top 5 Movie Recommendations"
    ),
    title="Movie Recommendation System",
    description=(
        "Enter a movie title to get five movies with similar genres. "
        "Recommendations are generated using TF-IDF and cosine similarity."
    ),
    examples=[
        ["Toy Story"],
        ["Jumanji"],
        ["Titanic"],
        ["Jurassic Park"]
    ]
)

demo.launch()